name: ip

on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run ip.py
        run: python ${{ github.workspace }}/ip.py



      - name: 提交更改
        run: |
          git config --local user.email "zjykyfy@qq.com"
          git config --local user.name "zjykyfy"
          git add .
          git commit *.txt -m "Add generated file"
          #git pull --rebase
          git push -f
